[package]
name = "fcm_microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
yup-oauth2 = "8.3"
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
hyper-rustls = "0.24"
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.5.2", features = ["trace", "cors"] }
