services:
  fcm_microservice:
    container_name: fcm_microservice
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./credentials:/app/credentials
      - ./data.db:/app/data.db
    env_file:
      - .env
    restart: unless-stopped
