services:
  fcm_microservice:
    container_name: fcm_microservice
    build: .
    ports:
      - "8084:8080"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    env_file:
      - .env
    restart: unless-stopped
